### PR TITLE
Implemented wrapper class for safe raw interface management

### PR DESCRIPTION
**Pull request by Fluxie**
The RawInterface class manages the reference counts of the interfaces and
calls Release for the interface when the wrapper is destroyed.
The interface of the RawInterface class has been mimicked
from std::unique_ptr.

### CODE REVIEW

**Comment by Rantanen** [comment]
The AppVeyor build fails since the wrappers are only used for the GCC build.

Perhaps we should do the following:
- Move the `test_lib.h`/`.c` one directory level up into the `cpp-raw` so it's available for both GCC and MSVC tests.
- GCC tests would still include it by default for all the tests while MSVC would use the `#import` wrappers by default for most of the tests.
- The wrapper tests would explicitly use `test_lib.h`/`.c` on both MSVC and GCC.
   - We might need to namespace the `#include` here to ensure it doesn't conflict with the `CLSID`/etc. provided by `#import` on MSVC. Or alternatively we need to remove the common `os` headers from the wrapper tests and use pure custom `#include`s there.

How does this sound?

**Comment by Rantanen** [comment]
I added the allocator tests to the `test_lib.cpp`/`test_lib.h`, which resulted in conflicts with this branch.

So as a result, I removed those two files from git. They are now generated through the cmake using the `test/cpp-raw/CMakeLists.txt`. There is also dedicated test-infra under `intercom/tests/generators` that can be used for tracking the changes in the generators. I believe that was the main reason these two files were in git instead of being generated?

The current test cases there are rather basic and not really that useful, but they should be rather easy to expand. Just modify the `test_lib.rs` or make a new one, such as `collection_tests.rs`. You can force update the target files (`.h`, `.cpp`, `.idl`, `.manifest`) by running the `cargo test --all-features` with `UPDATE_XYZ_TESTS=1` environment variable. This is included as part of the failure messages when `cargo test --all-features` fails.

**Comment by Fluxie** [comment]
Was there still something missing?

I excluded the interface_wrapper tests from MSVC for now. Support for creating the objects via the Activiator class on Windows platform needs to be imlemented before they can be enabled.

**Comment by Rantanen** [comment]
That works. Thanks!

**Pull request merged**
