### PR TITLE
Moved current tests to a compiler specific directory

### PR DESCRIPTION
**Pull request by Fluxie**
We need a place to write tests for gcc and clang.
The test directory called "cpp" was rather limiting.

NOTE: I could not test the compilation but I did try to
modify the project files accordingly.

### CODE REVIEW

**Comment by Fluxie** [comment]
I'm not sure I can fix the issue without access to Windows build environment.

**Comment by Rantanen** [comment]
Fixing the failure should be as simple as updating the paths in `scripts/ci.bat` and `scripts/test.ps1` to point to the new location.

However before we go through with this change, I'd like some resolution to #23.

If we consider the C++ tests as "baseline", then instead of moving them to completely different directory, I'd prefer something such as:

```
tests/
|
|- cpp-raw/
|  |- msvc/
|  |  |- platform.cpp
|  |  |- cpp-raw.sln
|  |  '- cpp-raw.vcproj
|  |
|  |- gcc/
|  |  |- platform.cpp
|  |  '- Makefile (?)
|  |
|  |- llvm/
|  |  |- platform.cpp
|  |  '- Makefile (?)
|  |
|  |- tests.cpp...
|  '- ...
|
|- cpp-api/
|  '- ...
|
'- cs/
   '- ...
```

Otherwise we'd need to duplicate most of our base tests between different platforms. We _will_ want to test the base functionality, such as ref counting, query interface, interface return, interface implementation, etc. on multiple platforms.

**Comment by Rantanen** [comment]
I went ahead and implemented my suggestion to fix the current issue.

- `/test/cpp-raw` contains platform agnostic sources for unit tests. These sources should not reference any platform libraries, etc. that make it impossible to use the code on other platforms.
- `/test/cpp-raw/os.h` - The os.h header is an exception to the above rule. Any conditional includes (such as the `TestLib_h.h` generated by midl on Windows) are included here - but these includes are hidden behind compiler defines.
- `/test/cpp-raw/msvc/` includes both the Visual Studio solution and project for compiling the tests as well as any MSVC specific sources that are needed for the test. At minimum this includes the definitions of the `InitializeRuntime`, `UniniailizeRuntime` and `CreateInstance` methods declared, but not defined, in `os.h`.

The project file is built in such a way that it references the sources using `*.cpp` wildcard. New test sources can be added in `test/cpp-raw` without the need to modify the Visual Studio project file.

If we can later expand these unit tests for other platforms, these same considerations should apply:
- Unit tests themselves can be compiled as-is on all platforms.
- Platform/compiler specific code resides in the platform sub-directory.
- New unit test sources can be added without having to modify the platform files.
  - These would be currently restricted to any new cpp-files immediately in the `test/cpp-raw/` directory.
  - Alternatively we could move the unit test files to `test/cpp-raw/tests/` directory or similar.
  - Point I'm trying to make is that "without modifying the platform files" doesn't exclude modifying the platform files once due to structural changes. We just don't want to modify them _every_ time we add a new unit test source.

If we later migrate the C++ tests on top of CMake or similar build system, we can either get rid of the `msvc` directory and use CMake for Windows builds or leave the `msvc` as a test and an example for those who wish to use Visual Studio without CMake. I have no preference either way.

**Comment by Rantanen** [comment]
If you still encounter issues with the current setup re-open this or suggest something else. I just wanted to ensure that we won't end up in a situation where the current C++ unit tests would be restricted to Windows if we can help it.

Also I didn't touch the C# tests here. Mono seems to be using [xbuild](http://www.mono-project.com/docs/tools+libraries/tools/xbuild/), which is msbuild compatible as far as I can tell. This could mean that there is a chance that the current `.csproj` is compatible with that.

In any case, I'd rather revisit the C# tests once that becomes a problem. Ideally if we end up supporting Mono on Linux, I'd rather share those tests between the platforms as well.

**Pull request closed without merging**
