### PR TITLE
Use "C" as the calling convention for non-Windows platforms

### PR DESCRIPTION
**Pull request by Fluxie**
This can be refined once a sane CMake setup has been established and
we can easily ask someone else to test the project on different platforms.

### CODE REVIEW

**Comment by Rantanen** [comment]
Oh yikes. This is going to make things interesting for testing. Mainly because now the default behavior will result in different call convention on Travis and Appveyor.

I was thinking of picking some low hanging issues out, such as #29, etc. But I guess we should tackle #18 first. In any case, we should aim for working Travis build for now as that's going to be the "cross platform, works everywhere" build in the future.

So update the call conventions in the `intercom-attributes/test/data/*.target.rs` files to refer to the "C" convention. This will break AppVeyor, but the `-gnu` build there is broken anyway thanks to `clippy` being broken.

Although it should only be broken for tests, not sure why it's breaking on compilation by complaining about "stdcall". :|

**Comment by Rantanen** [comment]
Oh, figured the "stdcall" issue. The string is `"\"stdcall\""`, so it includes the quotes. A string variable will be inserted as a string token with `#var` syntax.

So either use `-> &'static str { "stdcall" }` as with the `"C"`-convention, or then `-> Tokens { quote!( "stdcall" ) }` (and same for `"C"`).

I think I'd prefer the current `"C"` option, as that allows us to do matching/testing with strings easier in the future.

**Comment by Rantanen** [comment]
Concerning the final solution for the call convention, we have three options:

- `c_call` _feature_, which will force `extern "C"` on both platforms. By default this feature is not defined, which results in `extern "stdcall"` on Windows.
  - Upside: Easy to implement, "default" handling works fine and features are easy to use and common thing with many crates.
  - Downside: Features aren't really meant for this. Consider the following scenario: Crates A and B. Both of these depend on Intercom. B with default features, A with `c_call`. Normally `B` will export things with `"stdcall"` on Windows. However if A uses B as a dependency, then Intercom will be compiled with `c_call` and B will also end up using `extern "C"` on Windows.
- `call_conv = "c_call"` configuration option.
  - Upside: Allows `call_conf = "stdcall"` to force stdcall on Linux?
  - Donwide: No support in Cargo/Crates.toml, making this more or less unusable.
- Remove `intercom::com_interface`/`::com_class`/etc., replace with `intercom::call_convention::auto::com_interface`/... and `intercom::call_convention::c::com_interface`/...
  - Upside: Explicit. Allows `call_convention::stdcall::..` in the future.
  - Downside: Requires `use intercom::extern::auto::*;` even for the default case to work (or specifying the attributes with fully qualified path: `#[intercom::extern::auto::com_interface(...)]`.

The last one is the only one that "works correctly". Also I kind of like the explicitness of it. The loss of default handling is a bit meh, but I can live without it. I don't think Rust's IDE integration is good enough for people not to go by documentation/tutorials/etc. anyway, so it shouldn't be a major issue.

Essentially current Intercom code would look like:

```rust
extern crate intercom;
use intercom::call_convention::auto::*;

#[com_interface]
trait Foo {
   ...
}
```

Only the `use intercom::call_convention::auto::*;` line would need to be added.

Also I didn't think the downside of features being "inherited" was that critical - however if Intercom gets popular as a "COM server" (ie. for consuming COM components) and not just as a "COM client" (ie. for defining COM components), then crate B might want to depend on Intercom with "stdcall" to invoke... `XMLHttpRequest` (for example), which would not work, if A would specify `c_call`, that would make B define `XMLHttpRequest` interface with `extern "C"`.

With the explicit mods, B will define `XMLHttpRequest` using `auto::com_interface`, while A can define its own interfaces with `c::com_interface` and everything works just fine.

**Comment by Rantanen** [comment]
Ended up specifying #32 - however after all of that, I'm not sure if that is the right approach for now.

Instead we could leave the tests as "stdcall" and do a string replace on non-Windows machines from `extern "stdcall"` into `extern "C"` within the `intercom-attributes/test/lib.rs` before the equality comparison between the source and target code.

Reasoning for this is hidden somewhere within #32.

**Comment by Rantanen** [comment]
(Reason for "stdcall" -> "C" is purely that of entropy. "stdcall" is less likely to mean something other than the call convention, while "C" could technically accidentally appear in tests on its own and should not be replaced by "stdcall")

**Comment by Fluxie** [comment]
> Oh, figured the "stdcall" issue. The string is "\"stdcall\"", so it includes the quotes. A string variable will  be inserted as a string token with #var syntax.

Forgot to fix that. I sort of realized it because "C" worked without the quotation.

**Comment by Rantanen** [comment]
That looks good. The `nightly-gnu` AppVeyor build is broken thanks to Clippy so that failure is expected.

**Pull request merged**
